### ISSUE TITLE
H5端，限时购的倒计时貌似有BUG

### ISSUE THREAD

**Issue by cokeyang** [js-newbee/taro-yanxuan#14]
并没有按照预期有所显示

**Comment by js-newbee** [comment]
@cokeyang 麻烦截图看下，我这边电脑、手机看都正常

**Comment by cokeyang** [comment]
![image](https://user-images.githubusercontent.com/20353452/53873491-70217600-403b-11e9-90a8-68c5c0f4ac2e.png)
倒计时显示00:00:00
![image](https://user-images.githubusercontent.com/20353452/53873901-4452c000-403c-11e9-93d7-0c99c849d6f5.png)
这个地方的props.data.leftTime 是未定义。

**Comment by js-newbee** [comment]
@cokeyang 麻烦给下浏览器环境，我 debug 下

**Comment by cokeyang** [comment]
![image](https://user-images.githubusercontent.com/20353452/53874891-62212480-403e-11e9-9d46-9a0355dd723c.png)
![image](https://user-images.githubusercontent.com/20353452/53874913-6cdbb980-403e-11e9-842c-d3381e31d282.png)
![image](https://user-images.githubusercontent.com/20353452/53875805-5c2c4300-4040-11e9-9cc1-59075fddeb6b.png)

感觉是时序的问题。

**Comment by cokeyang** [comment]
加这段之后解决了
`  componentWillReceiveProps(nextProps) {
    this.setState({
      leftTime: parseInt((nextProps.data.leftTime || 0) / 1000)
    });
  }`

**Comment by js-newbee** [comment]
> 加这段之后解决了
> 
> > componentWillReceiveProps(nextProps) {
> > this.setState({
> > leftTime: parseInt((nextProps.data.leftTime || 0) / 1000)
> > });
> > }

嗯嗯，我修复了哈。之前这块考虑的不够严谨，因为 leftTime 是从 props 中取的，在 constructor 中初始化。如果后续数据更新了（比如 didShow 中又拉取了一次数据进行覆盖，这个时候就有问题了）

思路跟你一样，在 componentWillReceiveProps 里判断 props 的值是否发生了更新
