### ISSUE TITLE
Mac 运行npm run dev:weapp编译报错

### ISSUE THREAD

**Issue by XYRZX** [js-newbee/taro-yanxuan#17]
<img width="490" alt="image" src="https://user-images.githubusercontent.com/17899775/54806871-4f515580-4cb6-11e9-978b-d5bfafdb93f5.png">
你好，在使用命令npm run dev:weapp的时候报错了，第一次弄这个，有点懵

**Comment by js-newbee** [comment]
@XYRZX 我重新 clone 代码试了下，编译没有问题，也是 mac
有可能是依赖安装有问题，如果你是用 yarn 安装的，不妨换成 npm 重新试下
或者删掉 node_modules 重新安装一次，注意看下安装过程有无报错

**Comment by 580** [comment]
Mac OS 版本多少？
