### ISSUE TITLE
Clone到本地，无法导入到微信小程序

### ISSUE THREAD

**Issue by 1eez** [js-newbee/taro-yanxuan#19]
看WIKI说是支持微信小程序的，但是，导入微信小程序开发环境的时候提示：
无法找到app.json等文件，看了下pages下的文件格式，貌似也不是微信小程序的四文件格式。
![image](https://user-images.githubusercontent.com/17718224/54974375-cea09b00-4fce-11e9-9a11-6b5091a83483.png)

**Comment by 580** [comment]
目录定位到/dist试试？

**Comment by js-newbee** [comment]
@1eez 如楼上所示，编译后是在项目下的 dist 文件夹里，已在 README 中补充说明
