### ISSUE TITLE
taro build --type rn --watch failed

### ISSUE THREAD

**Issue by neuyu** [js-newbee/taro-yanxuan#2]
![image](https://user-images.githubusercontent.com/16551927/53061580-06f91900-34f9-11e9-8c44-e4124d7d62c5.png)

**Comment by js-newbee** [comment]
@neuyu 多谢反馈，这是 @tarojs/cli 已知问题，已补充到 README 中
请参考 https://github.com/NervJS/taro/issues/2121 中提到的临时方法解决下哈
