### ISSUE TITLE
TypeError: null is not an object (evaluating 'item.id')

### ISSUE THREAD

**Issue by Pines-Cheng** [js-newbee/taro-yanxuan#20]
报错如下，安卓和 iOS 都存在。

![image](https://user-images.githubusercontent.com/9441951/55133868-1146ac80-5162-11e9-8f6a-90d14a72f558.png)

注释掉 home.js 里面的

```js
          {/* 为你推荐 */}
          {/*<Recommend list={recommend} />*/}

```
就好了，初步判断是后台返回的数据有问题。

**Comment by js-newbee** [comment]
嗯嗯，是后端接口变动导致的，已更新
