### ISSUE TITLE
JSX结构问题

### ISSUE THREAD

**Issue by magicjoey** [js-newbee/taro-yanxuan#21]
Error: JSX map 循环参数暂时不支持使用 Object pattern 解构。
-----
  24 |         </View>
  25 |         <View className='home-recommend__list'>
> 26 |           {list.filter(item => item.type === 1).map(({ id, categoryItem }) => (
     |                                                     ^^^^^^^^^^^^^^^^^^^^

node版本v10.15.0   taro版本1.2.17  报这个结构问题，请问该如何解决

**Comment by js-newbee** [comment]
@magicjoey 谢谢反馈，昨天改得着急没验证支付宝的编译，已修改
