### ISSUE TITLE
谢谢

### ISSUE THREAD

**Issue by fakerd** [js-newbee/taro-yanxuan#22]
早上来面试，被你pass 掉了，有点不服，看了你的代码规范后，我现在服了，也多谢你的指导，如果可以的话，能否加下微信，以后能一起交流， 微信：muscle285768219 多谢了

**Comment by js-newbee** [comment]
对 Taro、小程序 这块感兴趣的话，可以关注我们的 Github、掘金账号，后续还会有更新，例如最新将开源我们 Taro 的脚手架，也是包含很多干货。
或者在 Taro 的 issue 中提问，我也经常在那回答相关问题。
也可以关注我们公司举办的技术沙龙，之前已经举办了2次，预计5、6月份会举办一次大前端主题的技术沙龙。

至于其他交流方式，不好意思，我也顾不来
