### ISSUE TITLE
请问如何登录？无法使用购物车功能

### ISSUE THREAD

**Issue by imageslr** [js-newbee/taro-yanxuan#27]
@js-newbee  您好，我在学习这个小程序的源码，但是目前微信登录和邮箱登录都无效了。主要想学习购物车的相关设计。

我想请问：加入购物车(dispatchAdd)、获取购物车商品数(dispatchCartNum)等接口的返回值都是一致吗？那么这些接口返回值（cartInfo）具体有哪些字段？可否贴个接口返回结果示例呢？谢谢！

**Comment by js-newbee** [comment]
他现在登录比较麻烦了，短时间内攻克不了。
如果你只是想看下相关接口结果的话，可以用 Charles 抓包看下~
之前我也是这么搞的，电脑上运行 Charles，手机连代理，去访问小程序就能看到请求情况了

**Comment by imageslr** [comment]
噢噢 好的 我试试

**Comment by x1nes** [comment]
说到登录：
src\pages\cart.js 61行
`          <Empty text='未登陆' />`
这里是错别字吧。
