### ISSUE TITLE
安卓7.0模拟器运行程序失败

### ISSUE THREAD

**Issue by ph2017** [js-newbee/taro-yanxuan#3]
安卓7.0模拟器运行程序失败，错误提示信息如下：
![image](https://user-images.githubusercontent.com/28702748/53084151-36c91080-353b-11e9-81bb-045c54dc0845.png)

Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'RCTRawText [text: ]' to a 'RCTView')
addChildAt
    ReactShadowNodeImpl.java:279
addChildAt
    ReactShadowNodeImpl.java:56
setChildren
    UIImplementation.java:482
setChildren
    UIManagerModule.java:441
invoke
    Method.java
invoke
    JavaMethodWrapper.java:372
invoke
    JavaModuleWrapper.java:160
run
    NativeRunnable.java
handleCallback
    Handler.java:751
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:29
loop
    Looper.java:154
run
    MessageQueueThreadImpl.java:192
run
    Thread.java:761

**Comment by zyh9** [comment]
![image](https://user-images.githubusercontent.com/26808622/53313143-f549b400-38f2-11e9-908f-6d583d0e9725.png)

**Comment by js-newbee** [comment]
@zyh9 赞！
