### ISSUE TITLE
求解答一下tabBar在登录 专区详情的页面中tabBar是display:none的，怎么实现呢？求解答一下，先谢谢了

### ISSUE THREAD

**Issue by curryhh** [js-newbee/taro-yanxuan#30]

**Comment by js-newbee** [comment]
@curryhh 建议好好看下小程序官方文档

小程序区分 tabBar 页面跟一般页面，在 config.tabBar 中定义的页面就是会有 tabBar，反之就不会有
另外也有 API 可以隐藏 tabBar

**Comment by curryhh** [comment]
@js-newbee 
看了下小程序的文档，小程序配置中的tabBar.list参数中的页面才会出现tabBar，其他则是隐藏的，我去试一试，谢谢大佬了
