### ISSUE TITLE
Win10上编译微信小程序报错麻烦看下

### ISSUE THREAD

**Issue by herseus** [js-newbee/taro-yanxuan#4]
![qq 20190221094526](https://user-images.githubusercontent.com/8351576/53137501-f2cb1f80-35bd-11e9-80ea-234846e7b41f.png)

**Comment by js-newbee** [comment]
“Fixed this issue by disabling Windows Defender - Controlled Folder Access.”

来源自 - https://stackoverflow.com/questions/48386990/create-react-app-range-error-maximum-call-stack-size-exceeded
