### ISSUE TITLE
npm run dev:rn的时候怎么调不起ios模拟器或者android模拟器呢?

### ISSUE THREAD

**Issue by labike** [js-newbee/taro-yanxuan#42]
我看taro文档中说npm run dev:rn运行的是rn_tmp内的代码，后面还要克隆个taro-native-shell, 这个东西是个空壳, 要用react-native run-ios/android跑起来，但是这两个怎么关联起来呢? 运行哪个可以调其模拟器.

**Comment by js-newbee** [comment]
`npm run dev:rn` 只是编译代码、启动 Metro Bundle 服务，这个时候访问 http://127.0.0.1:8081/rn_temp/index.bundle?platform=ios&dev=true 能看到 js 代码。

`taro-native-shell` 才是启动模拟器，启动模拟器、打开 app 后，加载的就是上面那个 bundle 的代码。

这两者的关系是这样的，你参考文档 https://taro-docs.jd.com/taro/docs/react-native.html 就好哈

**Comment by labike** [comment]
o . 谢谢
