### ISSUE TITLE
mac 环境下运行npm run dev:weapp报错

### ISSUE THREAD

**Issue by Miiskye** [js-newbee/taro-yanxuan#5]
![image](https://user-images.githubusercontent.com/28433071/53139217-f06bc400-35c3-11e9-825d-d1fedbcaca4f.png)

**Comment by Miiskye** [comment]
# 全局安装 @tarojs/cli 指定版本，或 npm install -g @tarojs/cli@1.2.13
yarn global add @tarojs/cli@1.2.13

# 安装依赖，或 npm i
yarn
这两个用yarn安装运行下面的命令会报错，用npm安装没问题

**Comment by js-newbee** [comment]
"sh: taro: command not found". 看提示是 tarojs/cli 没有正常安装。
谢谢反馈，不过这个就跟项目没有关系了
