### ISSUE TITLE
mac环境运行提示 unsafe-perm in lifecycle true

### ISSUE THREAD

**Issue by vangyong** [js-newbee/taro-yanxuan#9]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/11.10.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev:weapp' ]
2 info using npm@6.7.0
3 info using node@v11.10.0
4 verbose run-script [ 'predev:weapp', 'dev:weapp', 'postdev:weapp' ]
5 info lifecycle taro-yanxuan@1.0.0~predev:weapp: taro-yanxuan@1.0.0
6 info lifecycle taro-yanxuan@1.0.0~dev:weapp: taro-yanxuan@1.0.0
7 verbose lifecycle taro-yanxuan@1.0.0~dev:weapp: unsafe-perm in lifecycle true
8 verbose lifecycle taro-yanxuan@1.0.0~dev:weapp: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/wangyong/opensource/taro-yanxuan/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Wireshark.app/Contents/MacOS:/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home:/Users/wangyong/devsoftware/apache-maven-3.5.4/bin:/Users/wangyong/wisedoc/jtapp/build:/Users/wangyong/devsoftware/scala/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Wireshark.app/Contents/MacOS:/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home:/Users/wangyong/devsoftware/apache-maven-3.5.4/bin:/Users/wangyong/wisedoc/jtapp/build:/Users/wangyong/devsoftware/scala/bin:/Users/wangyong/devsoftware/gradle-4.4.1/bin:/usr/local/Cellar/go/1.10.2/libexec/bin:/Users/wangyong/gopath/bin:/Users/wangyong/toolsoftware/jmeter-4.0/bin
9 verbose lifecycle taro-yanxuan@1.0.0~dev:weapp: CWD: /Users/wangyong/opensource/taro-yanxuan
10 silly lifecycle taro-yanxuan@1.0.0~dev:weapp: Args: [ '-c', 'npm run build:weapp -- --watch' ]
11 silly lifecycle taro-yanxuan@1.0.0~dev:weapp: Returned: code: 1  signal: null
12 info lifecycle taro-yanxuan@1.0.0~dev:weapp: Failed to exec dev:weapp script
13 verbose stack Error: taro-yanxuan@1.0.0 dev:weapp: `npm run build:weapp -- --watch`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:197:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:197:13)
13 verbose stack     at maybeClose (internal/child_process.js:984:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid taro-yanxuan@1.0.0
15 verbose cwd /Users/wangyong/opensource/taro-yanxuan
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/Cellar/node/11.10.0/bin/node" "/usr/local/bin/npm" "run" "dev:weapp"
18 verbose node v11.10.0
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error taro-yanxuan@1.0.0 dev:weapp: `npm run build:weapp -- --watch`
22 error Exit status 1
23 error Failed at the taro-yanxuan@1.0.0 dev:weapp script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by js-newbee** [comment]
@vangyong 参考下 https://stackoverflow.com/questions/42308879/npm-err-code-elifecycle
这种问题一般没有好的解决方法，只能清缓存、重装尝试了
